export const mockList = {
  WET: {
    symbol: "WET",
    name: "SixEleven",
    name_full: "SixEleven (WET)",
    max_supply: 611000,
    icon_url: "https://assets.coinlayer.com/icons/611.png",
  },
  ABC: {
    symbol: "ABC",
    name: "AB-Chain",
    name_full: "AB-Chain (ABC)",
    max_supply: 2100000,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  ACP: {
    symbol: "ACP",
    name: "AC-Block",
    name_full: "AB-Chain (ABC)",
    max_supply: 2000000,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  ACT: {
    symbol: "ACT",
    name: "ACT-SYM",
    name_full: "AB-Chain (ABC)",
    max_supply: 78000000,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  ADA: {
    symbol: "ADA",
    name: "ADA-SLIM",
    name_full: "AB-Chain (ABC)",
    max_supply: 218500,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  ADCN: {
    symbol: "ADCN",
    name: "ADCN-AND",
    name_full: "AB-Chain (ABC)",
    max_supply: 544000000,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  ADL: {
    symbol: "ADL",
    name: "ADL-Chain",
    name_full: "AB-Chain (ABC)",
    max_supply: 45400000,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  ADX: {
    symbol: "ADX",
    name: "ADX-POP",
    name_full: "AB-Chain (ABC)",
    max_supply: 1770000000,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  ADZ: {
    symbol: "ADZ",
    name: "AZ-DEM",
    name_full: "AB-Chain (ABC)",
    max_supply: 2900000,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  AE: {
    symbol: "AE",
    name: "AE-XML",
    name_full: "AB-Chain (ABC)",
    max_supply: 3600000,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  AGI: {
    symbol: "AGI",
    name: "AER-AGI",
    name_full: "AB-Chain (ABC)",
    max_supply: 4589000,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  AIB: {
    symbol: "AIB",
    name: "AAIBB-BACK",
    name_full: "AB-Chain (ABC)",
    max_supply: 987855,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  AIDOC: {
    symbol: "AIDOC",
    name: "AAIDB-DOC",
    name_full: "AB-Chain (ABC)",
    max_supply: 4566678,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  AWS: {
    symbol: "AWS",
    name: "AWS-SER",
    name_full: "AB-Chain (ABC)",
    max_supply: 855525,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  AJIO: {
    symbol: "AJIO",
    name: "AB-Chain",
    name_full: "AB-Chain (ABC)",
    max_supply: 8971454,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  MYN: {
    symbol: "MYN",
    name: "MY-SAW",
    name_full: "AB-Chain (ABC)",
    max_supply: 79552366,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  CRP: {
    symbol: "CRP",
    name: "AS-ASE",
    name_full: "AB-Chain (ABC)",
    max_supply: 4512236,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  SET: {
    symbol: "SET",
    name: "ASETB-AQW",
    name_full: "AB-Chain (ABC)",
    max_supply: 4547896223,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  SEM: {
    symbol: "SEM",
    name: "AB-Chain",
    name_full: "AB-Chain (ABC)",
    max_supply: 5454112366,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
  QYT: {
    symbol: "QYT",
    name: "AB-Chain",
    name_full: "AB-Chain (ABC)",
    max_supply: 1489123,
    icon_url: "https://assets.coinlayer.com/icons/ABC.png",
  },
};

export const mockLive = {
  rates: {
    WET: 0.389165,
    ABC: 453.99,
    ACP: 100.99,
    ACT: 26555.99,
    ADA: 47.99,
    ADCN: 100.99,
    ADX: 96.99,
    ADL: 458.99,
    ADZ: 855.99,
    AE: 85.99,
    AGI: 1.99,
    AIB: 12.99,
    AIDOC: 59.99,
    AWS: 55.99,
    AJIO: 969.99,
    MYN: 5.99,
    CRP: 99.99,
    SET: 556.99,
    SEM: 554.99,
    QYT: 55.99,
  },
};
